[project]
name = "probe-droid-swgoh-bot"
version = "0.1.0"
description = "Bot de Discord para detectar códigos regalo y promociones de SWGoH"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "discord-py>=2.7.1",
    "feedparser>=6.0.12",
    "python-dotenv>=1.2.2",
    "requests>=2.33.0",
]
